# Generated by Django 6.0.5 on 2026-05-17 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_initial'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Numero')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood_name', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('event_type', models.CharField(choices=[('rally', 'Comicio'), ('meeting', 'Reuniao'), ('door_to_door', 'Porta a Porta'), ('carreata', 'Carreata'), ('debate', 'Debate'), ('community', 'Evento Comunitario'), ('fundraiser', 'Evento de Arrecadacao'), ('training', 'Treinamento')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('date', models.DateTimeField(verbose_name='Data/Hora')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora fim')),
                ('expected_attendees', models.IntegerField(default=0, verbose_name='Presenca esperada')),
                ('actual_attendees', models.IntegerField(default=0, verbose_name='Presenca real')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.city', verbose_name='Cidade')),
                ('contacts_attended', models.ManyToManyField(blank=True, related_name='attended_events', to='contacts.contact', verbose_name='Presentes')),
                ('contacts_invited', models.ManyToManyField(blank=True, related_name='invited_events', to='contacts.contact', verbose_name='Convidados')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.region', verbose_name='Regiao')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-date'],
            },
        ),
    ]
