# Generated by Django 6.0.5 on 2026-05-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('geography', '0002_alter_macroregion_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='actual_attendees',
            field=models.IntegerField(default=0, verbose_name='Presença real'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('rally', 'Comício'), ('meeting', 'Reunião'), ('door_to_door', 'Porta a Porta'), ('carreata', 'Carreata'), ('debate', 'Debate'), ('community', 'Evento Comunitário'), ('fundraiser', 'Evento de Arrecadação'), ('training', 'Treinamento')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='expected_attendees',
            field=models.IntegerField(default=0, verbose_name='Presença esperada'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='event',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.region', verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
