# Generated by Django 6.0.5 on 2026-05-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('geography', '0002_alter_macroregion_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.region', verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('coordinator_state', 'Coordenador Estadual'), ('coordinator_region', 'Coordenador Regional'), ('coordinator_city', 'Coordenador Municipal'), ('coordinator_neighborhood', 'Coordenador de Bairro'), ('volunteer', 'Voluntário'), ('viewer', 'Visualizador')], default='viewer', max_length=30, verbose_name='Função'),
        ),
    ]
