# Generated by Django 6.0.5 on 2026-05-17 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_cities',
            field=models.ManyToManyField(blank=True, to='geography.city', verbose_name='Cidades alvo'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_regions',
            field=models.ManyToManyField(blank=True, to='geography.region', verbose_name='Regioes alvo'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atribuido a'),
        ),
        migrations.AddField(
            model_name='task',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='campaigns.campaign', verbose_name='Campanha'),
        ),
        migrations.AddField(
            model_name='task',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.city', verbose_name='Cidade'),
        ),
    ]
