# Generated by Django 6.0.5 on 2026-05-17 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', 'due_date'], 'verbose_name': 'Demanda', 'verbose_name_plural': 'Demandas'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Concluida em'),
        ),
        migrations.AddField(
            model_name='task',
            name='goal_achieved',
            field=models.IntegerField(default=0, verbose_name='Resultado obtido'),
        ),
        migrations.AddField(
            model_name='task',
            name='goal_description',
            field=models.CharField(blank=True, help_text='Ex: conquistar 50 apoiadores', max_length=255, verbose_name='Meta da demanda'),
        ),
        migrations.AddField(
            model_name='task',
            name='phase',
            field=models.CharField(choices=[('planned', 'Planejada'), ('articulating', 'Em Articulacao'), ('scheduled', 'Agendada'), ('executed', 'Executada'), ('completed', 'Concluida')], db_index=True, default='planned', max_length=20, verbose_name='Fase'),
        ),
        migrations.AddField(
            model_name='task',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='geography.region', verbose_name='Regiao'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('meeting', 'Reuniao com lideranca'), ('event', 'Evento presencial'), ('field_visit', 'Visita de campo'), ('party_work', 'Articulacao partidaria'), ('communication', 'Acao de comunicacao'), ('recruitment', 'Captacao de apoiador')], default='field_visit', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Atribuido a'),
        ),
        migrations.AlterField(
            model_name='task',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='campaigns.campaign', verbose_name='Campanha'),
        ),
        migrations.AlterField(
            model_name='task',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='geography.city', verbose_name='Cidade'),
        ),
    ]
