# Generated by Django 6.0.5 on 2026-05-17 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_task_kanban_fields'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('start_date', models.DateField(verbose_name='Data inicio')),
                ('end_date', models.DateField(verbose_name='Data fim')),
                ('status', models.CharField(choices=[('planned', 'Planejado'), ('confirmed', 'Confirmado'), ('in_progress', 'Em Andamento'), ('completed', 'Concluido')], default='planned', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsavel')),
                ('target_regions', models.ManyToManyField(blank=True, to='geography.region', verbose_name='Regioes')),
            ],
            options={
                'verbose_name': 'Roteiro',
                'verbose_name_plural': 'Roteiros',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Data')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='Hora prevista')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('travel_minutes', models.PositiveIntegerField(default=0, help_text='Tempo ate a proxima parada', verbose_name='Deslocamento (min)')),
                ('is_overnight', models.BooleanField(default=False, verbose_name='Pernoite')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.city', verbose_name='Cidade')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='campaigns.itinerary', verbose_name='Roteiro')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_stops', to='campaigns.task', verbose_name='Demanda')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['date', 'order'],
            },
        ),
    ]
