# Generated by Django 6.0.5 on 2026-05-17 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_itinerary_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('briefing', 'Briefing'), ('social_post', 'Post redes sociais'), ('whatsapp', 'Material WhatsApp'), ('photo', 'Registro fotografico'), ('video', 'Video'), ('press', 'Nota de imprensa')], max_length=20, verbose_name='Tipo')),
                ('phase', models.CharField(choices=[('before', 'Antes da acao'), ('after', 'Depois da acao')], max_length=10, verbose_name='Fase')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_production', 'Em producao'), ('approved', 'Aprovado'), ('published', 'Publicado')], default='pending', max_length=20, verbose_name='Status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('file', models.FileField(blank=True, upload_to='contents/', verbose_name='Arquivo')),
                ('publication_url', models.URLField(blank=True, verbose_name='URL de publicacao')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsavel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='campaigns.task', verbose_name='Demanda')),
            ],
            options={
                'verbose_name': 'Conteudo',
                'verbose_name_plural': 'Conteudos',
                'ordering': ['phase', 'due_date'],
            },
        ),
    ]
