# Generated by Django 6.0.5 on 2026-05-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_content_model'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='origin_city',
            field=models.ForeignKey(blank=True, help_text='Cidade de onde o candidato parte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries_origin', to='geography.city', verbose_name='Cidade de saida'),
        ),
    ]
