# Generated by Django 6.0.5 on 2026-05-20 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_itinerary_origin_city'),
        ('geography', '0002_alter_macroregion_options_alter_region_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['phase', 'due_date'], 'verbose_name': 'Conteúdo', 'verbose_name_plural': 'Conteúdos'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(verbose_name='Data início'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('planned', 'Planejada'), ('active', 'Ativa'), ('paused', 'Pausada'), ('completed', 'Concluída')], default='planned', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_regions',
            field=models.ManyToManyField(blank=True, to='geography.region', verbose_name='Regiões alvo'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('briefing', 'Briefing'), ('social_post', 'Post redes sociais'), ('whatsapp', 'Material WhatsApp'), ('photo', 'Registro fotográfico'), ('video', 'Vídeo'), ('press', 'Nota de imprensa')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='content',
            name='phase',
            field=models.CharField(choices=[('before', 'Antes da ação'), ('after', 'Depois da ação')], max_length=10, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='content',
            name='publication_url',
            field=models.URLField(blank=True, verbose_name='URL de publicação'),
        ),
        migrations.AlterField(
            model_name='content',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_production', 'Em produção'), ('approved', 'Aprovado'), ('published', 'Publicado')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='origin_city',
            field=models.ForeignKey(blank=True, help_text='Cidade de onde o candidato parte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraries_origin', to='geography.city', verbose_name='Cidade de saída'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(verbose_name='Data início'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='status',
            field=models.CharField(choices=[('planned', 'Planejado'), ('confirmed', 'Confirmado'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído')], default='planned', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='target_regions',
            field=models.ManyToManyField(blank=True, to='geography.region', verbose_name='Regiões'),
        ),
        migrations.AlterField(
            model_name='itinerarystop',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='itinerarystop',
            name='travel_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Tempo até a próxima parada', verbose_name='Deslocamento (min)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='task',
            name='phase',
            field=models.CharField(choices=[('planned', 'Planejada'), ('articulating', 'Em Articulação'), ('scheduled', 'Agendada'), ('executed', 'Executada'), ('completed', 'Concluída')], db_index=True, default='planned', max_length=20, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='task',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='geography.region', verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('meeting', 'Reunião com liderança'), ('event', 'Evento presencial'), ('field_visit', 'Visita de campo'), ('party_work', 'Articulação partidária'), ('communication', 'Ação de comunicação'), ('recruitment', 'Captação de apoiador')], default='field_visit', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
