# Generated by Django 6.0.5 on 2026-05-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Numero')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood_name', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Setor')),
                ('employees_count', models.IntegerField(default=0, verbose_name='Funcionarios')),
                ('partnership_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de parceria')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
            ],
            options={
                'verbose_name': 'Empresa Parceira',
                'verbose_name_plural': 'Empresas Parceiras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Rua')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Numero')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood_name', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='Apelido')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('category', models.CharField(choices=[('coordenador_regional', 'Coordenador Regional'), ('coordenador_municipal', 'Coordenador Municipal'), ('coordenador_bairro', 'Coordenador de Bairro'), ('apoiador', 'Apoiador'), ('parceiro', 'Parceiro'), ('lideranca', 'Lideranca Comunitaria'), ('vereador', 'Vereador'), ('prefeito', 'Prefeito'), ('deputado', 'Deputado'), ('eleitor', 'Eleitor'), ('indeciso', 'Indeciso'), ('oposicao', 'Oposicao')], default='eleitor', max_length=30, verbose_name='Categoria')),
                ('engagement_level', models.IntegerField(choices=[(1, 'Frio - Sem contato'), (2, 'Morno - Primeiro contato'), (3, 'Quente - Engajado'), (4, 'Muito Quente - Ativo na campanha'), (5, 'Embaixador - Multiplica votos')], default=1, verbose_name='Nivel de engajamento')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='Profissao')),
                ('party', models.CharField(blank=True, max_length=50, verbose_name='Partido')),
                ('voter_registration', models.CharField(blank=True, max_length=20, verbose_name='Titulo de eleitor')),
                ('electoral_zone', models.CharField(blank=True, max_length=10, verbose_name='Zona eleitoral')),
                ('electoral_section', models.CharField(blank=True, max_length=10, verbose_name='Secao eleitoral')),
                ('photo', models.ImageField(blank=True, upload_to='contacts/photos/', verbose_name='Foto')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('phone_call', 'Ligacao'), ('whatsapp', 'WhatsApp'), ('meeting', 'Reuniao'), ('event', 'Evento'), ('door_to_door', 'Porta a Porta'), ('social_media', 'Rede Social'), ('email', 'E-mail'), ('referral', 'Indicacao')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('outcome', models.CharField(blank=True, max_length=255, verbose_name='Resultado')),
                ('next_action', models.CharField(blank=True, max_length=255, verbose_name='Proxima acao')),
                ('next_action_date', models.DateField(blank=True, null=True, verbose_name='Data proxima acao')),
            ],
            options={
                'verbose_name': 'Interacao',
                'verbose_name_plural': 'Interacoes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
    ]
