# Generated by Django 6.0.5 on 2026-05-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('coordenador_regional', 'Coordenador Regional'), ('coordenador_municipal', 'Coordenador Municipal'), ('coordenador_bairro', 'Coordenador de Bairro'), ('apoiador', 'Apoiador'), ('parceiro', 'Parceiro'), ('lideranca', 'Lideranca Comunitaria'), ('vereador', 'Vereador'), ('prefeito', 'Prefeito'), ('deputado', 'Deputado'), ('eleitor', 'Eleitor'), ('indeciso', 'Indeciso'), ('oposicao', 'Oposicao')], db_index=True, default='eleitor', max_length=30, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='engagement_level',
            field=models.IntegerField(choices=[(1, 'Frio - Sem contato'), (2, 'Morno - Primeiro contato'), (3, 'Quente - Engajado'), (4, 'Muito Quente - Ativo na campanha'), (5, 'Embaixador - Multiplica votos')], db_index=True, default=1, verbose_name='Nivel de engajamento'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
    ]
