# Generated by Django 6.0.5 on 2026-05-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_category_and_more'),
        ('geography', '0002_alter_macroregion_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Interação', 'verbose_name_plural': 'Interações'},
        ),
        migrations.AlterField(
            model_name='companypartner',
            name='employees_count',
            field=models.IntegerField(default=0, verbose_name='Funcionários'),
        ),
        migrations.AlterField(
            model_name='companypartner',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='companypartner',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('coordenador_regional', 'Coordenador Regional'), ('coordenador_municipal', 'Coordenador Municipal'), ('coordenador_bairro', 'Coordenador de Bairro'), ('apoiador', 'Apoiador'), ('parceiro', 'Parceiro'), ('lideranca', 'Liderança Comunitária'), ('vereador', 'Vereador'), ('prefeito', 'Prefeito'), ('deputado', 'Deputado'), ('eleitor', 'Eleitor'), ('indeciso', 'Indeciso'), ('oposicao', 'Oposição')], db_index=True, default='eleitor', max_length=30, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='electoral_section',
            field=models.CharField(blank=True, max_length=10, verbose_name='Seção eleitoral'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='engagement_level',
            field=models.IntegerField(choices=[(1, 'Frio - Sem contato'), (2, 'Morno - Primeiro contato'), (3, 'Quente - Engajado'), (4, 'Muito Quente - Ativo na campanha'), (5, 'Embaixador - Multiplica votos')], db_index=True, default=1, verbose_name='Nível de engajamento'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profession',
            field=models.CharField(blank=True, max_length=200, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='geography.region', verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='voter_registration',
            field=models.CharField(blank=True, max_length=20, verbose_name='Título de eleitor'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('phone_call', 'Ligação'), ('whatsapp', 'WhatsApp'), ('meeting', 'Reunião'), ('event', 'Evento'), ('door_to_door', 'Porta a Porta'), ('social_media', 'Rede Social'), ('email', 'E-mail'), ('referral', 'Indicação')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='next_action',
            field=models.CharField(blank=True, max_length=255, verbose_name='Próxima ação'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='next_action_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data próxima ação'),
        ),
    ]
