# Generated by Django 6.0.5 on 2026-05-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'E-mail')], max_length=20, verbose_name='Canal')),
                ('target_filter', models.JSONField(blank=True, default=dict, verbose_name='Filtro de contatos')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendada'), ('sending', 'Enviando'), ('sent', 'Enviada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Status')),
                ('total_sent', models.IntegerField(default=0, verbose_name='Total enviados')),
                ('total_delivered', models.IntegerField(default=0, verbose_name='Total entregues')),
                ('total_read', models.IntegerField(default=0, verbose_name='Total lidos')),
                ('total_replied', models.IntegerField(default=0, verbose_name='Total respondidos')),
            ],
            options={
                'verbose_name': 'Campanha de Mensagem',
                'verbose_name_plural': 'Campanhas de Mensagens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'E-mail')], max_length=20, verbose_name='Canal')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='Variaveis')),
            ],
            options={
                'verbose_name': 'Template de Mensagem',
                'verbose_name_plural': 'Templates de Mensagens',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('group_type', models.CharField(choices=[('coordination', 'Coordenacao'), ('supporters', 'Apoiadores'), ('volunteers', 'Voluntarios'), ('campaign', 'Campanha')], max_length=50, verbose_name='Tipo')),
                ('member_count', models.IntegerField(default=0, verbose_name='Membros')),
                ('invite_link', models.URLField(blank=True, verbose_name='Link de convite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Grupo WhatsApp',
                'verbose_name_plural': 'Grupos WhatsApp',
                'ordering': ['name'],
            },
        ),
    ]
