# Generated by Django 6.0.5 on 2026-05-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        ('contacts', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecampaign',
            name='target_contacts',
            field=models.ManyToManyField(blank=True, to='contacts.contact', verbose_name='Contatos alvo'),
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.messagetemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='admin_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact', verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.city', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.region', verbose_name='Regiao'),
        ),
    ]
