# Generated by Django 6.0.5 on 2026-05-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
        ('geography', '0002_alter_macroregion_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='content',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='variables',
            field=models.JSONField(blank=True, default=list, verbose_name='Variáveis'),
        ),
        migrations.AlterField(
            model_name='whatsappgroup',
            name='group_type',
            field=models.CharField(choices=[('coordination', 'Coordenação'), ('supporters', 'Apoiadores'), ('volunteers', 'Voluntários'), ('campaign', 'Campanha')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='whatsappgroup',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.region', verbose_name='Região'),
        ),
    ]
