# Generated by Django 6.0.5 on 2026-05-17 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='Numero do recibo')),
                ('method', models.CharField(choices=[('pix', 'PIX'), ('transfer', 'Transferencia'), ('cash', 'Especie'), ('crowdfunding', 'Financiamento Coletivo')], max_length=30, verbose_name='Metodo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='contacts.contact', verbose_name='Doador')),
            ],
            options={
                'verbose_name': 'Doacao',
                'verbose_name_plural': 'Doacoes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255, verbose_name='Descricao')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria')),
                ('receipt', models.FileField(blank=True, upload_to='expenses/receipts/', verbose_name='Recibo')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-date'],
            },
        ),
    ]
