# Generated by Django 6.0.5 on 2026-05-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-date'], 'verbose_name': 'Doação', 'verbose_name_plural': 'Doações'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='method',
            field=models.CharField(choices=[('pix', 'PIX'), ('transfer', 'Transferência'), ('cash', 'Espécie'), ('crowdfunding', 'Financiamento Coletivo')], max_length=30, verbose_name='Método'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número do recibo'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
    ]
