# Generated by Django 6.0.5 on 2026-05-29 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_interaction_options_and_more'),
        ('fundraising', '0002_alter_donation_options_alter_donation_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='comissao_apoiador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão apoiador (3%)'),
        ),
        migrations.AddField(
            model_name='donation',
            name='comissao_coordenador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão coordenador (7%)'),
        ),
        migrations.AddField(
            model_name='donation',
            name='comissao_plataforma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão plataforma (10%)'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_cpf',
            field=models.CharField(blank=True, db_index=True, max_length=14, verbose_name='CPF do doador'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do doador'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do doador'),
        ),
        migrations.AddField(
            model_name='donation',
            name='pix_status',
            field=models.CharField(blank=True, choices=[('pending', 'Aguardando'), ('paid', 'Pago'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], max_length=20, verbose_name='Status PIX'),
        ),
        migrations.AddField(
            model_name='donation',
            name='pix_txid',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='PIX TXID'),
        ),
        migrations.AddField(
            model_name='donation',
            name='valor_candidato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor candidato (80%)'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='method',
            field=models.CharField(choices=[('pix', 'PIX'), ('transfer', 'Transferência'), ('cash', 'Espécie'), ('crowdfunding', 'Financiamento Coletivo'), ('online', 'Doação Online')], max_length=30, verbose_name='Método'),
        ),
        migrations.CreateModel(
            name='Captador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('coordenador', 'Coordenador'), ('apoiador', 'Apoiador')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('slug', models.SlugField(max_length=12, unique=True, verbose_name='Código único')),
                ('qrcode_image', models.ImageField(blank=True, upload_to='fundraising/qrcodes/', verbose_name='QR Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('saldo_disponivel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo disponível')),
                ('total_arrecadado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total arrecadado')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='captador', to='contacts.contact', verbose_name='Contato')),
                ('coordenador', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'coordenador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apoiadores', to='fundraising.captador', verbose_name='Coordenador responsável')),
            ],
            options={
                'verbose_name': 'Captador',
                'verbose_name_plural': 'Captadores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='captador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes_captadas', to='fundraising.captador', verbose_name='Captador'),
        ),
        migrations.CreateModel(
            name='SolicitacaoResgate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('pago', 'Pago'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status')),
                ('nota_fiscal', models.FileField(blank=True, upload_to='fundraising/notas_fiscais/', verbose_name='Nota Fiscal')),
                ('dados_bancarios', models.JSONField(blank=True, default=dict, verbose_name='Dados bancários')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('captador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates', to='fundraising.captador', verbose_name='Captador')),
            ],
            options={
                'verbose_name': 'Solicitação de Resgate',
                'verbose_name_plural': 'Solicitações de Resgate',
                'ordering': ['-created_at'],
            },
        ),
    ]
