# Generated by Django 6.0.5 on 2026-05-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('election_type', models.CharField(choices=[('federal_deputy', 'Deputado Federal'), ('state_deputy', 'Deputado Estadual'), ('senator', 'Senador'), ('governor', 'Governador'), ('president', 'Presidente'), ('mayor', 'Prefeito'), ('councilor', 'Vereador')], max_length=20, verbose_name='Tipo')),
                ('round_number', models.IntegerField(default=1, verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Eleicao',
                'verbose_name_plural': 'Eleicoes',
                'unique_together': {('year', 'election_type', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='CandidateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.CharField(max_length=255, verbose_name='Candidato')),
                ('candidate_number', models.CharField(max_length=10, verbose_name='Numero')),
                ('party', models.CharField(max_length=50, verbose_name='Partido')),
                ('votes', models.IntegerField(default=0, verbose_name='Votos')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual')),
                ('is_elected', models.BooleanField(default=False, verbose_name='Eleito')),
                ('is_sorgatto', models.BooleanField(default=False, verbose_name='Sorgatto')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_results', to='geography.city', verbose_name='Cidade')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='elections.election', verbose_name='Eleicao')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['-votes'],
            },
        ),
        migrations.CreateModel(
            name='VoteGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('state', 'Estado'), ('macro_region', 'Macro Regiao'), ('region', 'Regiao'), ('city', 'Municipio'), ('neighborhood', 'Bairro')], max_length=20, verbose_name='Nivel')),
                ('target_votes', models.IntegerField(default=0, verbose_name='Meta de votos')),
                ('current_estimate', models.IntegerField(default=0, verbose_name='Estimativa atual')),
                ('election_year', models.IntegerField(default=2026, verbose_name='Ano da eleicao')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_goals', to='geography.city')),
                ('macro_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_goals', to='geography.macroregion')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_goals', to='geography.neighborhood')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_goals', to='geography.region')),
            ],
            options={
                'verbose_name': 'Meta de Votos',
                'verbose_name_plural': 'Metas de Votos',
            },
        ),
    ]
