# Generated by Django 6.0.5 on 2026-05-17 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.CharField(max_length=255, verbose_name='Candidato')),
                ('candidate_number', models.CharField(max_length=10, verbose_name='Numero')),
                ('party', models.CharField(max_length=50, verbose_name='Partido')),
                ('zone_number', models.CharField(max_length=10, verbose_name='Zona Eleitoral')),
                ('votes', models.IntegerField(default=0, verbose_name='Votos')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual')),
                ('is_sorgatto', models.BooleanField(default=False, verbose_name='Sorgatto')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_election_results', to='geography.city', verbose_name='Cidade')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_results', to='elections.election', verbose_name='Eleicao')),
            ],
            options={
                'verbose_name': 'Resultado por Zona',
                'verbose_name_plural': 'Resultados por Zona',
                'ordering': ['zone_number', '-votes'],
            },
        ),
    ]
