# Generated by Django 6.0.5 on 2026-05-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_zoneresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'verbose_name': 'Eleição', 'verbose_name_plural': 'Eleições'},
        ),
        migrations.AlterField(
            model_name='candidateresult',
            name='candidate_number',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='candidateresult',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='elections.election', verbose_name='Eleição'),
        ),
        migrations.AlterField(
            model_name='votegoal',
            name='election_year',
            field=models.IntegerField(default=2026, verbose_name='Ano da eleição'),
        ),
        migrations.AlterField(
            model_name='votegoal',
            name='level',
            field=models.CharField(choices=[('state', 'Estado'), ('macro_region', 'Macro Região'), ('region', 'Região'), ('city', 'Município'), ('neighborhood', 'Bairro')], max_length=20, verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='zoneresult',
            name='candidate_number',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='zoneresult',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_results', to='elections.election', verbose_name='Eleição'),
        ),
    ]
