# Generated by Django 6.0.5 on 2026-05-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_election_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresult',
            name='party',
            field=models.CharField(max_length=150, verbose_name='Partido'),
        ),
        migrations.AlterField(
            model_name='zoneresult',
            name='party',
            field=models.CharField(max_length=150, verbose_name='Partido'),
        ),
    ]
