# Generated by Django 6.0.5 on 2026-05-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField()),
                ('ibge_code', models.CharField(max_length=10, unique=True, verbose_name='Codigo IBGE')),
                ('population', models.IntegerField(default=0, verbose_name='Populacao')),
                ('registered_voters', models.IntegerField(default=0, verbose_name='Eleitores')),
                ('geojson', models.JSONField(blank=True, null=True, verbose_name='GeoJSON')),
                ('mayor_name', models.CharField(blank=True, max_length=200, verbose_name='Prefeito')),
                ('mayor_party', models.CharField(blank=True, max_length=50, verbose_name='Partido do prefeito')),
                ('num_vereadores', models.IntegerField(default=0, verbose_name='Vereadores')),
                ('num_vereadores_pl', models.IntegerField(default=0, verbose_name='Vereadores PL')),
                ('pl_executive_president', models.CharField(blank=True, max_length=200, verbose_name='Presidente executiva PL')),
                ('economic_matrix', models.TextField(blank=True, verbose_name='Matriz economica')),
                ('votes_sorgatto_2022', models.IntegerField(default=0, verbose_name='Votos Sorgatto 2022')),
                ('meta_votes', models.IntegerField(default=0, verbose_name='Meta de votos')),
                ('electoral_zone', models.CharField(blank=True, max_length=50, verbose_name='Zona eleitoral')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MacroRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True)),
                ('population', models.IntegerField(default=0, verbose_name='Populacao')),
                ('geojson', models.JSONField(blank=True, null=True, verbose_name='GeoJSON')),
                ('color', models.CharField(default='#3388ff', max_length=7, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Macro Regiao',
                'verbose_name_plural': 'Macro Regioes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ElectoralZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone_number', models.CharField(max_length=10, verbose_name='Numero da zona')),
                ('registered_voters', models.IntegerField(default=0, verbose_name='Eleitores')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Local')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electoral_zones', to='geography.city', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Zona Eleitoral',
                'verbose_name_plural': 'Zonas Eleitorais',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Sigla')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Nome completo')),
                ('slug', models.SlugField(unique=True)),
                ('population', models.IntegerField(default=0, verbose_name='Populacao')),
                ('geojson', models.JSONField(blank=True, null=True, verbose_name='GeoJSON')),
                ('svg_path_id', models.CharField(blank=True, max_length=50, verbose_name='ID no SVG')),
                ('meta_votes', models.IntegerField(default=0, verbose_name='Meta de votos')),
                ('color', models.CharField(default='#3388ff', max_length=7, verbose_name='Cor')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_regions', to='contacts.contact', verbose_name='Coordenador')),
                ('macro_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='geography.macroregion', verbose_name='Macro Regiao')),
            ],
            options={
                'verbose_name': 'Regiao',
                'verbose_name_plural': 'Regioes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geography.region', verbose_name='Regiao'),
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField()),
                ('population', models.IntegerField(default=0, verbose_name='Populacao')),
                ('geojson', models.JSONField(blank=True, null=True, verbose_name='GeoJSON')),
                ('meta_votes', models.IntegerField(default=0, verbose_name='Meta de votos')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='geography.city', verbose_name='Cidade')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_neighborhoods', to='contacts.contact', verbose_name='Coordenador')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'ordering': ['name'],
                'unique_together': {('slug', 'city')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('slug', 'region')},
        ),
    ]
