# Generated by Django 6.0.5 on 2026-05-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macroregion',
            options={'ordering': ['name'], 'verbose_name': 'Macro Região', 'verbose_name_plural': 'Macro Regiões'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Região', 'verbose_name_plural': 'Regiões'},
        ),
        migrations.AlterField(
            model_name='city',
            name='economic_matrix',
            field=models.TextField(blank=True, verbose_name='Matriz econômica'),
        ),
        migrations.AlterField(
            model_name='city',
            name='ibge_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código IBGE'),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=0, verbose_name='População'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geography.region', verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='electoralzone',
            name='zone_number',
            field=models.CharField(max_length=10, verbose_name='Número da zona'),
        ),
        migrations.AlterField(
            model_name='macroregion',
            name='population',
            field=models.IntegerField(default=0, verbose_name='População'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='population',
            field=models.IntegerField(default=0, verbose_name='População'),
        ),
        migrations.AlterField(
            model_name='region',
            name='macro_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='geography.macroregion', verbose_name='Macro Região'),
        ),
        migrations.AlterField(
            model_name='region',
            name='population',
            field=models.IntegerField(default=0, verbose_name='População'),
        ),
    ]
