# Generated by Django 6.0.5 on 2026-05-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_alter_macroregion_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='meta_doacoes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Meta de doações (R$)'),
        ),
    ]
