# Generated by Django 6.0.5 on 2026-05-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_add_meta_doacoes_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='meta_doacoes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Meta de doações (R$)'),
        ),
    ]
